#!/bin/bash
if [ -f "/boot/backup" ]; then
	echo Backing up rootfs
	if [ -n "$(which dcfldd)" ]; then
	  dcfldd if=/dev/mmcblk0p3 of=/rootfs.img bs=4M status=on statusinterval=4
	else
	  # status only in later versions of coreutils package
	  dd if=/dev/mmcblk0p3 of=/rootfs.img conv=fsync bs=4M #status=progress 
	fi
	unlink /boot/backup
	/boot/boot_to_root
fi
exit 0
