#!/bin/bash

# to get the partition uuid
source /boot/rescue_helpers.sh

# ensure / is on recoveryfs
if [ "$(rootpart_label)" != "recoveryfs" ]; then
  echo "to be run only when / is mounted on partition 'recoveryfs'"
  exit
fi

#inFile=/dev/mmcblk0p3
inFile=/dev/disk/by-label/rootfs

if [ -f "/boot/backup" ]; then
  # script triggered backup
  echo Backing up rootfs
  # status only in later versions of coreutils package
  #dd if="$inFile" of=/rootfs.img conv=fsync status=progress bs=4M
  dd if="$inFile" of=/rootfs.img conv=fsync bs=4M
  unlink /boot/backup
  /boot/boot_to_root
else
  # status output only makes sense in interactive session
  read -p "Backing up rootfs to /rootfs.img ? (N/y): " ans
  [ "$ans" != "y" ] && echo "ABORTING." && exit 1

  if [ -n "$(which dcfldd)" ]; then
	dcfldd if="$inFile" of=/rootfs.img bs=4M status=on statusinterval=4
  else
	# status only in later versions of coreutils package
	dd if="$inFile" of=/rootfs.img conv=fsync bs=4M #status=progress 
  fi
fi
exit 0
