#!/bin/bash
# NOTE: this should only be run when on recovery
#	- as it requires sufficient space on the / to contain the backup image
# TODO: implement check

if [ -f "/boot/backup" ]; then
  # script triggered backup
  echo Backing up rootfs
  # status only in later versions of coreutils package
  dd if=/dev/mmcblk0p3 of=/rootfs.img conv=fsync bs=4M #status=progress 

  unlink /boot/backup
  /boot/boot_to_root
else
  # status output only makes sense in interactive session
  read -p "Backing up rootfs to /rootfs.img ? (N/y): " ans
  [ "$ans" != "y" ] && echo "ABORTING." && exit 1

  if [ -n "$(which dcfldd)" ]; then
	dcfldd if=/dev/mmcblk0p3 of=/rootfs.img bs=4M status=on statusinterval=4
  else
	# status only in later versions of coreutils package
	dd if=/dev/mmcblk0p3 of=/rootfs.img conv=fsync bs=4M #status=progress 
  fi
fi
exit 0
