#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# to get the partition uuid
source /boot/rescue_helpers.sh

if [ "$(rootpart_label)" == "rootfs" ]; then
    echo "/ is mounted on partition 'rootfs' already"
    exit
fi

echo Rebooting to root partition in 5 seconds
sleep 5
# changing boot partition to rootfs
#   part: 2 to 3
#sed -i 's/-02/-03/' /boot/cmdline.txt
#sed -i 's/\(root=PARTUUID=\w\+\)-02/\1-03/' /boot/cmdline.txt
# for non UUID addressing
#sed -i 's?\(root=/dev/\w\+\)p2?\1p3?' /boot/cmdline.txt

#   solution requiring labeled partition
#part_label="rootfs"
#partuuid=$(lsblk -r -o label,PARTUUID | grep "$part_label" | cut -f2 -d' ')
partuuid=$(partlabel_uuid "rootfs")
sed -i 's/\(root=PARTUUID=\)\S\+/\1'${partuuid}'/' /boot/cmdline.txt

touch /boot/ssh
reboot
exit 0
