#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo Rebooting to root partition in 5 seconds
sleep 5
#sed -i 's/-02/-03/' /boot/cmdline.txt
sed -i 's/\(root=PARTUUID=\w\+\)-02/\1-03/' /boot/cmdline.txt
# for non UUID addressing
#sed -i 's?\(root=/dev/\w\+\)p2?\1p3?' /boot/cmdline.txt
touch /boot/ssh
reboot
exit 0
