#!/bin/bash

# to get the partition uuid
source /boot/rescue_helpers.sh

# ensure / is on recoveryfs
if [ "$(rootpart_label)" != "recoveryfs" ]; then
  echo "to be run only when / is mounted on partition 'recoveryfs'"
  exit
fi

#outFile=/dev/mmcblk0p3
outFile=/dev/disk/by-label/rootfs 

if [ -f "/boot/restore" ]; then
  # script triggered restore
  echo Restoring rootfs
  # status only in later versions of coreutils package
  #dd if=/rootfs.img of="$outFile" conv=fsync status=progress bs=4M
  dd if=/rootfs.img of="$outFile" conv=fsync status=progress bs=4M
  unlink /boot/restore
  /boot/boot_to_root
else
  # status output only makes sense in interactive session
  read -p "Restoring rootfs from /rootfs.img ? (N/y): " ans
  [ "$ans" != "y" ] && echo "ABORTING." && exit 1

  if [ -n "$(which dcfldd)" ]; then
	dcfldd if=/rootfs.img of="$outFile" bs=4M status=on statusinterval=4
  else
	# status only in later versions of coreutils package
	dd if=/rootfs.img of="$outFile" conv=fsync bs=4M #status=progress 
  fi
fi
exit 0
